# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interactive_filter_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 480, 741, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filter_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.filter_button.setObjectName("filter_button")
        self.horizontalLayout.addWidget(self.filter_button)
        self.save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.lock_asset_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.lock_asset_button.setObjectName("lock_asset_button")
        self.horizontalLayout.addWidget(self.lock_asset_button)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.graph = QtWidgets.QFrame(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(20, 20, 741, 451))
        self.graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graph.setObjectName("graph")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.graph)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 741, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.contract_label_title_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contract_label_title_label.sizePolicy().hasHeightForWidth())
        self.contract_label_title_label.setSizePolicy(sizePolicy)
        self.contract_label_title_label.setObjectName("contract_label_title_label")
        self.horizontalLayout_3.addWidget(self.contract_label_title_label)
        self.current_contract_show_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_contract_show_label.sizePolicy().hasHeightForWidth())
        self.current_contract_show_label.setSizePolicy(sizePolicy)
        self.current_contract_show_label.setText("")
        self.current_contract_show_label.setObjectName("current_contract_show_label")
        self.horizontalLayout_3.addWidget(self.current_contract_show_label)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.graph)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(580, 40, 160, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.robust_covariance_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.robust_covariance_button.setObjectName("robust_covariance_button")
        self.verticalLayout_2.addWidget(self.robust_covariance_button)
        self.one_class_svm_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.one_class_svm_button.setObjectName("one_class_svm_button")
        self.verticalLayout_2.addWidget(self.one_class_svm_button)
        self.isolation_forest_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.isolation_forest_button.setObjectName("isolation_forest_button")
        self.verticalLayout_2.addWidget(self.isolation_forest_button)
        self.local_outlier_factor_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.local_outlier_factor_button.setObjectName("local_outlier_factor_button")
        self.verticalLayout_2.addWidget(self.local_outlier_factor_button)
        self.textBrowser = QtWidgets.QTextBrowser(self.graph)
        self.textBrowser.setGeometry(QtCore.QRect(0, 40, 581, 411))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 530, 741, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.asset_symbol_combobox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.asset_symbol_combobox.setObjectName("asset_symbol_combobox")
        self.asset_symbol_combobox.addItem("")
        self.asset_symbol_combobox.addItem("")
        self.asset_symbol_combobox.addItem("")
        self.asset_symbol_combobox.addItem("")
        self.asset_symbol_combobox.addItem("")
        self.asset_symbol_combobox.addItem("")
        self.asset_symbol_combobox.addItem("")
        self.asset_symbol_combobox.addItem("")
        self.asset_symbol_combobox.addItem("")
        self.asset_symbol_combobox.addItem("")
        self.horizontalLayout_2.addWidget(self.asset_symbol_combobox)
        self.asset_expiry_combobox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asset_expiry_combobox.sizePolicy().hasHeightForWidth())
        self.asset_expiry_combobox.setSizePolicy(sizePolicy)
        self.asset_expiry_combobox.setEditable(False)
        self.asset_expiry_combobox.setObjectName("asset_expiry_combobox")
        self.asset_expiry_combobox.addItem("")
        self.asset_expiry_combobox.addItem("")
        self.asset_expiry_combobox.addItem("")
        self.asset_expiry_combobox.addItem("")
        self.horizontalLayout_2.addWidget(self.asset_expiry_combobox)
        self.strike_lower_bond_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.strike_lower_bond_lineEdit.setObjectName("strike_lower_bond_lineEdit")
        self.horizontalLayout_2.addWidget(self.strike_lower_bond_lineEdit)
        self.strike_upper_bound_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.strike_upper_bound_lineEdit.setObjectName("strike_upper_bound_lineEdit")
        self.horizontalLayout_2.addWidget(self.strike_upper_bound_lineEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.filter_button.setText(_translate("MainWindow", "Filter"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.lock_asset_button.setText(_translate("MainWindow", "Lock On Asset"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.contract_label_title_label.setText(_translate("MainWindow", "Current Contract Filtering:  "))
        self.robust_covariance_button.setText(_translate("MainWindow", "Robust Covariane"))
        self.one_class_svm_button.setText(_translate("MainWindow", "One-Class SVM"))
        self.isolation_forest_button.setText(_translate("MainWindow", "Isolation Forest"))
        self.local_outlier_factor_button.setText(_translate("MainWindow", "Local Outlier Factor"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.asset_symbol_combobox.setItemText(0, _translate("MainWindow", "XLB"))
        self.asset_symbol_combobox.setItemText(1, _translate("MainWindow", "XLE"))
        self.asset_symbol_combobox.setItemText(2, _translate("MainWindow", "XLF"))
        self.asset_symbol_combobox.setItemText(3, _translate("MainWindow", "XLI"))
        self.asset_symbol_combobox.setItemText(4, _translate("MainWindow", "XLK"))
        self.asset_symbol_combobox.setItemText(5, _translate("MainWindow", "XLP"))
        self.asset_symbol_combobox.setItemText(6, _translate("MainWindow", "XLU"))
        self.asset_symbol_combobox.setItemText(7, _translate("MainWindow", "XLV"))
        self.asset_symbol_combobox.setItemText(8, _translate("MainWindow", "XLY"))
        self.asset_symbol_combobox.setItemText(9, _translate("MainWindow", "SPX"))
        self.asset_expiry_combobox.setItemText(0, _translate("MainWindow", "20190118"))
        self.asset_expiry_combobox.setItemText(1, _translate("MainWindow", "20190215"))
        self.asset_expiry_combobox.setItemText(2, _translate("MainWindow", "20190315"))
        self.asset_expiry_combobox.setItemText(3, _translate("MainWindow", "20190418"))

